// font-subset: skip (본문 글만: 장식 글꼴 대상이 아니다 — tools/fonts/collect.ts)
// 물어보기 화면의 본문 안내 문구. 한 문장씩 나눠 둔다(번들 한글 장문 검사 G7).
export const COPY = {
  intro1: "아이 행동이 궁금하면 적어 주세요.",
  intro2: "집 PC가 기록을 보고 답해요.",
  off1: "집 PC가 꺼져 있어요.",
  off2: "켜지면 답변해요.",
  bodyLabel: "궁금한 것",
  bodyHint: "예: 밥 먹을 때 자꾸 숟가락을 던져요",
  many1: "질문을 너무 많이 보냈어요.",
  many2: "잠시 뒤에 다시 해 주세요.",
  sendFail: "보내지 못했어요. 다시 해 주세요.",
  pickWho: "질문하는 사람을 골라 주세요.",
  none: "아직 질문이 없어요.",
  redBadge: "위급 신호",
  noteLabel: "해 봤어요 메모",
  noteHint: "예: 안아 주니 금방 그쳤어요",
  noteGuide: "해 본 방법과 결과를 적으면 다음 답변에 반영돼요",
  voteUp: "도움이 됐어요",
  voteDown: "도움이 안 됐어요",
  voteSaved1: "반영했어요.",
  voteSaved2: "다음 답변에 참고해요.",
  voteCleared: "표를 취소했어요.",
  voteFail: "저장하지 못했어요. 다시 해 주세요.",
  voteMine: "내 표",
  reasonTitle: "어떤 점이 아쉬웠나요?",
  reasonText: "더 알려 주고 싶은 점(선택)",
  reaskMax: "다시 답변은 세 번까지예요.",
  reasonHelp: "아쉬운 점을 하나 골라 주세요.",
  reasonChange: "이유 바꾸기·다시 답변 받기",
  voteDownSaved: "표를 남겼어요. 아쉬운 점을 골라 주세요.",
  reaskSent: "다시 답변을 요청했어요.",
  voteLine: "가족 의견:",
  copyFail: "복사하지 못했어요. 글을 길게 눌러 복사해 주세요.",
  shareBtn: "공유하기",
  copyBtn: "복사하기",
  shareRange: "보낼 내용",
  shareShort: "짧게",
  shareLong: "자세히",
  reaskFail: "다시 요청하지 못했어요. 잠시 뒤에 해 주세요.",
  reaskLine1: "다시 작성 중이에요.",
  reaskLine2: "조금만 기다려 주세요.",
  reaskPending: "다시 작성을 기다리는 중이에요.",
  reaskReview: "다시 쓴 답을 검토하는 중이에요.",
  oldAnswerN: "이전 답변",
  shareCopied: "복사했어요.",
  shareWarn: "공유한 글은 앱 밖으로 나가요.",
  shareWarn2: "앱 링크는 가족 PIN이 있어야 열려요.",
  noteFail: "남기지 못했어요. 다시 해 주세요.",
  noInstant: "비슷한 알림장이나 자료를 찾지 못했어요.",
  offWait: "집 PC가 켜지면 답변해요.",
  fail1: "답을 만들지 못했어요.",
  fail2: "다시 질문해 주세요.",
  noAnswer: "답변을 불러오지 못했어요.",
  notFound: "찾는 질문이 없어요.",
  delNote: "지우면 목록에서 사라져요.",
  delFail: "지우지 못했어요. 다시 해 주세요.",
} as const;
